### ISSUE TITLE
Intermittent failures in io.vertx.ext.dropwizard.MetricsTest.testHttpMetricsResponseCode

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-dropwizard-metrics#33]
```
Starting test: MetricsTest#testHttpMetricsResponseCode 
java.lang.AssertionError: Was expecting responses-3xx to be not null
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at io.vertx.test.core.AsyncTestBase.assertNotNull(AsyncTestBase.java:390)
	at io.vertx.ext.dropwizard.MetricsTest.lambda$test$30(MetricsTest.java:310)
	at io.vertx.ext.dropwizard.MetricsTest$$Lambda$254/1687627235.handle(Unknown Source)
	at io.vertx.ext.dropwizard.MetricsTest.lambda$test$32(MetricsTest.java:327)
	at io.vertx.ext.dropwizard.MetricsTest$$Lambda$256/1276544608.handle(Unknown Source)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$14(HttpServerImpl.java:296)
	at io.vertx.core.http.impl.HttpServerImpl$$Lambda$79/220813571.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
	at io.vertx.core.impl.ContextImpl$$Lambda$34/1422238463.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
Unhandled exception 
java.lang.AssertionError: Was expecting responses-3xx to be not null
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at io.vertx.test.core.AsyncTestBase.assertNotNull(AsyncTestBase.java:390)
	at io.vertx.ext.dropwizard.MetricsTest.lambda$test$30(MetricsTest.java:310)
	at io.vertx.ext.dropwizard.MetricsTest$$Lambda$254/1687627235.handle(Unknown Source)
	at io.vertx.ext.dropwizard.MetricsTest.lambda$test$32(MetricsTest.java:327)
	at io.vertx.ext.dropwizard.MetricsTest$$Lambda$256/1276544608.handle(Unknown Source)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$14(HttpServerImpl.java:296)
	at io.vertx.core.http.impl.HttpServerImpl$$Lambda$79/220813571.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
	at io.vertx.core.impl.ContextImpl$$Lambda$34/1422238463.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:372)
	at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:592)
	at io.vertx.ext.dropwizard.MetricsTest.test(MetricsTest.java:329)
	at io.vertx.ext.dropwizard.MetricsTest.testHttpMetricsResponseCode(MetricsTest.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by tsegismont** [comment]
It appears this is due to:

```java
    // A little clunky, but it's possible we got here after closed has been called
    if (closed) {
      removeAll();
    }
```
in `io.vertx.ext.dropwizard.impl.TCPMetricsImpl#disconnected`

When this is commented out, the test passes.

The reason the test fails now is that it starts/closes an http client/server pair several times in a row, using the same host and port. Sometimes, after the client (or the server) has been closed, the disconnected (channel inactive) event is fired, and then all metrics for the host:port are removed. But they have been created again in the meantime, for a new server which is not closed yet...

I don't understand yet why we need to remove all the metrics if closed has been called. Because if closed has been called, the metrics have been removed already. Does someone have any idea?

**Comment by cescoffier** [comment]
The `removeAll` is required as some metrics are not removed beforehand. Unfortunately I'm not able to reproduce it locally. Any hint ?

**Comment by tsegismont** [comment]
IIRC I found this bug while checking CI.

To reproduce it I believe I have marked the method with the Repeat annotation

**Comment by cescoffier** [comment]
I used the repeat annotation, 100 times and still no bug... Definitely related to speed. I need to check if we are not reusing the same metrics instance.

**Comment by tsegismont** [comment]
@cescoffier can you have a look? Thx

**Comment by vietj** [comment]
LGTM
