### ISSUE TITLE
VertxMetricsImpl.createHttpClientMetrics should use a ConcurrentMap

### ISSUE THREAD

**Issue by pertyjons** [vert-x3/vertx-dropwizard-metrics#89]
Hi, 
Noticed a new error after testing Java 11 again after the recent updates to 3.6.2 and 3.6.3 with the Metrics client reporters.

If you start several vertices with WebClient.create you get a ConcurrentModificationException in the computeIfAbsent in vertxMetricsImpl:
```
HttpClientReporter reporter = (HttpClientReporter)this.clientReporters.computeIfAbsent(baseName, (n) -> {
   return new HttpClientReporter(this.registry, baseName, (SocketAddress)null);
  });

```

Here is the full stacktrace:

```
Feb 08, 2019 4:06:23 PM io.vertx.core.impl.DeploymentManager
SEVERE: NULL
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1139)
	at io.vertx.ext.dropwizard.impl.VertxMetricsImpl.createHttpClientMetrics(VertxMetricsImpl.java:125)
	at io.vertx.core.http.impl.HttpClientImpl.<init>(HttpClientImpl.java:114)
	at io.vertx.core.impl.VertxImpl.createHttpClient(VertxImpl.java:310)
	at io.vertx.ext.web.client.WebClient.create(WebClient.java:66)
	at com.vertx.test.WebClientTest.start(WebClientTest.java:16)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:494)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:841)

```

I'm attaching an maven example archive to reproduce the error running "OpenJDK 64-Bit Server VM (build 11+5-Ubuntu-1, mixed mode)"

[web-client-test.zip](https://github.com/vert-x3/issues/files/2845622/web-client-test.zip)

**Comment by vietj** [comment]
thanks for reporting

**Comment by chefhoobajoob** [comment]
We've also encountered this issue on 3.6.3, though with `Vertx.createHttpClient` and unfortunately don't have an option to run on an earlier jvm. Any recommendations?
