### ISSUE TITLE
Nullpointer in EventBusMetricsImpl

### ISSUE THREAD

**Issue by simon1212** [vert-x3/vertx-dropwizard-metrics#90]
We get a Nullpointer Exception in EventBusMetricsImpl when a handler is unregistered.
A null check in line 122 on HandlerMetric would help to avoid this Exception. We don't know why a null HandlerMetric can be passed here. Also other HandlerMetric consuming methods of this class could benefit from becoming null-safe.

Here is our stack-trace:

```
2.4.2019 08:11:0006:11:00.149  [vert.x-eventloop-thread-6] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
2.4.2019 08:11:00java.lang.NullPointerException: null
2.4.2019 08:11:00	at io.vertx.ext.dropwizard.impl.EventBusMetricsImpl.handlerUnregistered(EventBusMetricsImpl.java:122)
2.4.2019 08:11:00	at io.vertx.ext.dropwizard.impl.EventBusMetricsImpl.handlerUnregistered(EventBusMetricsImpl.java:34)
2.4.2019 08:11:00	at io.vertx.core.eventbus.impl.HandlerHolder.setRemoved(HandlerHolder.java:48)
2.4.2019 08:11:00	at io.vertx.core.eventbus.impl.EventBusImpl.removeLocalRegistration(EventBusImpl.java:307)
2.4.2019 08:11:00	at io.vertx.core.eventbus.impl.EventBusImpl.removeRegistration(EventBusImpl.java:289)
2.4.2019 08:11:00	at io.vertx.core.eventbus.impl.HandlerRegistration.doUnregister(HandlerRegistration.java:176)
2.4.2019 08:11:00	at io.vertx.core.eventbus.impl.HandlerRegistration.unregister(HandlerRegistration.java:135)
2.4.2019 08:11:00	at io.vertx.ext.web.handler.sockjs.impl.SockJSSocketBase.close(SockJSSocketBase.java:87)
2.4.2019 08:11:00	at io.vertx.ext.web.handler.sockjs.impl.SockJSSession.shutdown(SockJSSession.java:333)
2.4.2019 08:11:00	at io.vertx.ext.web.handler.sockjs.impl.WebSocketTransport$WebSocketListener.lambda$new$0(WebSocketTransport.java:99)
2.4.2019 08:11:00	at io.vertx.core.http.impl.WebSocketImplBase.handleClosed(WebSocketImplBase.java:454)
2.4.2019 08:11:00	at io.vertx.core.http.impl.Http1xServerConnection.handleClosed(Http1xServerConnection.java:474)
2.4.2019 08:11:00	at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$5(VertxHandler.java:164)
2.4.2019 08:11:00	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
2.4.2019 08:11:00	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
2.4.2019 08:11:00	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
2.4.2019 08:11:00	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
2.4.2019 08:11:00	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:164)
2.4.2019 08:11:00	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
2.4.2019 08:11:00	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
2.4.2019 08:11:00	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
2.4.2019 08:11:00	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
2.4.2019 08:11:00	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
2.4.2019 08:11:00	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
2.4.2019 08:11:00	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
2.4.2019 08:11:00	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
2.4.2019 08:11:00	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
```

**Comment by jotak** [comment]
Seems to be the same as https://github.com/vert-x3/vertx-micrometer-metrics/issues/74

**Comment by simon1212** [comment]
Yes I can confirm. This looks like micrometer implemenation is having the same problems with null HandlerMetrics.

**Comment by vietj** [comment]
I think we need to fix this in Vert.x Core instead as this seems to be a race there.

**Comment by vietj** [comment]
fixed by https://github.com/eclipse-vertx/vert.x/pull/2901
