### ISSUE TITLE
NPE in EventBusMetricsImpl on delivering message while handler registration is not finished yet

### ISSUE THREAD

**Issue by champeric** [vert-x3/vertx-dropwizard-metrics#95]
```
SEVERE: Unhandled exception
java.lang.NullPointerException
  at io.vertx.ext.dropwizard.impl.EventBusMetricsImpl.scheduleMessage(EventBusMetricsImpl.java:133)
  at io.vertx.ext.dropwizard.impl.EventBusMetricsImpl.scheduleMessage(EventBusMetricsImpl.java:34)
  at io.vertx.core.eventbus.impl.EventBusImpl.deliverToHandler(EventBusImpl.java:524)
  at io.vertx.core.eventbus.impl.EventBusImpl.deliverMessageLocally(EventBusImpl.java:395)
  at io.vertx.core.eventbus.impl.EventBusImpl.deliverMessageLocally(EventBusImpl.java:356)
  at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.onSubsReceived(ClusteredEventBus.java:241)
  at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$sendOrPub$8(ClusteredEventBus.java:228)
  at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMultiMap.lambda$null$6(HazelcastAsyncMultiMap.java:156)
  at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
  at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
  at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
```
This seems to be exactly the same problem as vert-x3/vertx-micrometer-metrics#81.

This is using Vert.x 3.8.4.

Basically, this happens when I register a consumer at an address and immediately after send a message to the address.

**Comment by LarsKrogJensen** [comment]
We are seeing this with dropwizard metrics randomly, on vertx 3.8.4
Would be nice to see some kind of guarding to avoid the NPE

**Comment by tsegismont** [comment]
@LarsKrogJensen  @champeric there have been a few changes in handler registration and metrics management in 3.8.5. Can you try with this version?
